fix: external reference type predicate
protobom/storage pull request #41
Opened 2024-11-08 20:47 UTC by jhoward-lm

This PR fixes the `backend.GetExternalReferencesByDocumentID` method and adds test cases to test the fix.

2024-11-09 00:11 UTC, cpanato requested changes
Test failure

2024-11-11 16:26 UTC, jhoward-lm commented
@ashearin @lallevato-lm @lmphil please review

2024-11-11 18:49 UTC, jhoward-lm commented
@cpanato Can you resolve your review and approve if you have no other comments?

2024-11-11 19:40 UTC, cpanato approved these changes

2024-11-11 19:40 UTC, merged